### ISSUE TITLE
Unable to find version `latest`

### ISSUE THREAD

**Issue by bytehead** [D3rHase/rsync-deploy-action#3]
Following the readme, my action errors like this:

```
Error: Unable to resolve action `d3rhase/rsync-deploy-action@latest`, unable to find version `latest`
```

Fixed by using `uses: D3rHase/rsync-deploy-action@v0.2`.

Maybe you could add a tag for `latest` as well?

**Comment by D3rHase** [comment]
Of course, I'll add that later.

**Comment by bytehead** [comment]
Thank you! 🙏🏼
